
-- Define PqC G as the power quandle of the conjugacy classes of G. 
-- What is Gr PqC G? Is it the infamous A? Doesn't work for cyclic groups, isn't true in general.

-- Gr PqC G is the free abelian group generated by conjugacy classes [a] and relations [a^n] = [a]^n

-- Do it at least for F_S

-- Are power quandles always decomposable as conjugacy classes? Are conjugacy classes sub-power-quandles? No, not closed under power...

-- What else can we say about conjugacy classes? 

-- It is Gr Cc Pq G ≃* Ab (Gr Pq G) which is sometimes A × Ab(G) (when Gr Pq G ≃* G × A)
